name: "PR Backend"

on:
  pull_request:
    paths:
      - "backend/**"

jobs:
  check-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: checkout
        uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: install the dependencies
        run: npm install
      - name: run test
        env:
          MONGODB_CONNECTION_STRING: ${{ secrets.MONGODB_CONNECTION_STRING }}
        run: npm run test
